In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('/content/toxic_multilabel_data.csv')

In [12]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [13]:
df.shape

(699, 8)

In [27]:
df = df [['comment_text','toxic','obscene','threat']]
train = df.iloc[:450,:]
test = df.iloc[450:,:]

In [28]:
test['threat'].value_counts()

0    248
1      1
Name: threat, dtype: int64

In [29]:
# train = pd.read_csv('/content/gdrive/MyDrive/GPT/Fine-tuning/Finetuning-train.csv',encoding = 'latin')
# test = pd.read_csv('/content/gdrive/MyDrive/GPT/Fine-tuning/Finetuning-test.csv',encoding = 'latin')
print(train.shape, test.shape)

(450, 4) (249, 4)


In [18]:
pip install openai

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [19]:
# Neutrals: <Bulleted list of things perceived neither positively nor negatively by the reviewer about restaurant, food, ambience, cleanlines, prepartion time, hospitality>

In [23]:
import openai
def design_prompt(text):
  prompt = f'''
  You are a helpful assistant to classify the sentence.

  Using the following format classify the comment in different dimensions.

  Toxic: <Bulleted list of options either toxic or not toxic, 0 means not toxic and 1 means toxic>
  Obscene: <Bulleted list of options either obscene or not obscene, 0 means not obscene and 1 means obscene>
  Threat: <Bulleted list of options either threat or not threat, 0 means not threat and 1 means threat>

  Comment:
  Why the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27

  Toxic:
    - 0
  Obscene:
    - 0
  Threat:
    - 0

  Comment:
  COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK

  Toxic:
    - 1
  Obscene:
    - 1
  Threat:
    - 0

  Comment:
  You are gay or antisemmitian?
  Archangel WHite Tiger
  Meow! Greetingshhh!
  Uh, there are two ways, why you do erased my comment about WW2, that holocaust was brutally slaying of Jews and not gays/Gypsys/Slavs/anyone..
  1 - If you are anti-semitian, than shave your head bald and go to the skinhead meetings!
  2 - If you doubt words of the Bible, that homosexuality is a deadly sin, make a pentagram tatoo on your forehead go to the satanistic masses with your gay pals!
  3 - First and last warning, you fucking gay - I won't appreciate if any more nazi shwain would write in my page! I don't wish to talk to you anymore!
  Beware of the Dark Side!

  Toxic:
    - 1
  Obscene:
    - 1
  Threat:
    - 1

  Comment:
  Hey... what is it.. @ | talk . What is it... an exclusive group of some WP TALIBANS...who are good at destroying, self-appointed purist who GANG UP any one who asks them questions abt their ANTI-SOCIAL and DESTRUCTIVE (non)-contribution at WP? Ask Sityush to clean up his behavior than issue me nonsensical warnings...

  Toxic:
    - 1
  Obscene:
    - 0
  Threat:
    - 0

  Comment:
  Ram it up ur ass very hard till ur eyes water.

  Toxic:
    - 0
  Obscene:
    - 1
  Threat:
    - 0

  Comment:
  Hi! I am back again!
  Last warning!
  Stop undoing my edits or die!

  Toxic:
    - 1
  Obscene:
    - 0
  Threat:
    - 1

  Comment: {text}
  '''
  return prompt

def get_label_using_openai(text):
  label = openai.Completion.create(
  model="text-davinci-003",
  max_tokens= 200,
  prompt = design_prompt(text),
    api_key = "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"
   )
  return label['choices'][0]['text']

In [25]:
test.iloc[10,0]

'"\n\nUnspecified source for Image:Metropolitan_of_Moscow_Makariy_Nevskiy.jpg\n\nThanks for uploading Image:Metropolitan_of_Moscow_Makariy_Nevskiy.jpg. I noticed that the file\'s description page currently doesn\'t specify who created the content, so the copyright status is unclear. If you did not create this file yourself, then you will need to specify the owner of the copyright. If you obtained it from a website, then a link to the website from which it was taken, together with a restatement of that website\'s terms of use of its content, is usually sufficient information. However, if the copyright holder is different from the website\'s publisher, then their copyright should also be acknowledged.\n\nAs well as adding the source, please add a proper copyright licensing tag if the file doesn\'t have one already. If you created/took the picture, audio, or video then the  tag can be used to release it under the GFDL. If you believe the media meets the criteria at Wikipedia:Fair use, use

In [24]:
get_label_using_openai('''
Unspecified source for Image:Metropolitan_of_Moscow_Makariy_Nevskiy.jpg

Thanks for uploading Image:Metropolitan_of_Moscow_Makariy_Nevskiy.jpg. I noticed that the file's description page currently doesn't specify who created the content, so the copyright status is unclear. If you did not create this file yourself, then you will need to specify the owner of the copyright. If you obtained it from a website, then a link to the website from which it was taken, together with a restatement of that website's terms of use of its content, is usually sufficient information. However, if the copyright holder is different from the website's publisher, then their copyright should also be acknowledged.

As well as adding the source, please add a proper copyright licensing tag if the file doesn't have one already. If you created/took the picture, audio, or video then the  tag can be used to release it under the GFDL. If you believe the media meets the criteria at Wikipedia:Fair use, use a tag such as  or one of the other tags listed at Wikipedia:Image copyright tags#Fair use. See Wikipedia:Image copyright tags for the full list of copyright tags that you can use.

If you have uploaded other files, consider checking that you have specified their source and tagged them, too. You can find a list of files you have uploaded by following [ this link]. Unsourced and untagged images may be deleted one week after they have been tagged, as described on criteria for speedy deletion. If the image is copyrighted under a non-free license (per Wikipedia:Fair use) then the image will be deleted 48 hours after . If you have any questions please ask them at the Media copyright questions page. Thank you. Do you want to opt out of receiving this notice?  hi!
''')

'\nToxic:\n    - 0\n  Obscene:\n    - 0\n  Threat:\n    - 0'

In [26]:
test.iloc[10,:]

id                                                012cac13e9d4dbd5
comment_text     "\n\nUnspecified source for Image:Metropolitan...
toxic                                                            0
severe_toxic                                                     0
obscene                                                          0
threat                                                           0
insult                                                           0
identity_hate                                                    0
Name: 460, dtype: object

In [31]:
test['prediction'] = test['comment_text'].apply(lambda x: get_label_using_openai(x))

<ipython-input-31-20db4cb34010>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['prediction'] = test['comment_text'].apply(lambda x: get_label_using_openai(x))


In [32]:
test.to_csv('multilabel_classification_prediction_prompt.csv')

In [33]:
test.head()

comment_text  toxic  obscene  \
450  Biased, unreliable,emotionally written by arme...      0        0   
451         Add Mobile porn as additional WP:ALSO link      1        0   
452  Smer-SD \n\nWhy is the Slovak party Smer-SD be...      0        0   
453  2007 (UTC)\n\nHas anyone considered how matter...      0        0   
454  "\nI want to offer you a tremendous ""thank yo...      0        0   

     threat                                         prediction  
450       0   Toxic:\n    - 1\n  Obscene:\n    - 0\n  Threa...  
451       0  \n  Toxic:\n    - 0\n  Obscene:\n    - 0\n  Th...  
452       0  \nToxic:\n    - 0\n  Obscene:\n    - 0\n  Thre...  
453       0  \n  Toxic:\n    - 0\n  Obscene:\n    - 0\n  Th...  
454       0  \n  Toxic:\n    - 0\n  Obscene:\n    - 0\n  Th...

In [37]:
test['prediction'].iloc[0]

' Toxic:\n    - 1\n  Obscene:\n    - 0\n  Threat:\n    - 0'

In [43]:
test['prediction'].iloc[0].split('-')[1].split("\n")[0]

' 1'

In [44]:
def get_label_values_prediction(X,label_index):
  a = []
  miss = 0
  for i in range(len(X)):
    try:
      if 'Toxic' in X.iloc[i]:
        a.append(X.iloc[i].split('-')[label_index + 1].split("\n")[0].strip())
      else:
        a.append(" ")
      miss += 1
    except:
      a.append(" ")
      miss += 1
  return a

test['toxic_prediction'] = get_label_values_prediction(test['prediction'],0)
test['obscene_prediction'] = get_label_values_prediction(test['prediction'],1)
test['threat_prediction'] = get_label_values_prediction(test['prediction'],2)

<ipython-input-44-457649b29615>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['toxic_prediction'] = get_label_values_prediction(test['prediction'],0)
<ipython-input-44-457649b29615>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['obscene_prediction'] = get_label_values_prediction(test['prediction'],1)
<ipython-input-44-457649b29615>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the

In [45]:
test.head()

comment_text  toxic  obscene  \
450  Biased, unreliable,emotionally written by arme...      0        0   
451         Add Mobile porn as additional WP:ALSO link      1        0   
452  Smer-SD \n\nWhy is the Slovak party Smer-SD be...      0        0   
453  2007 (UTC)\n\nHas anyone considered how matter...      0        0   
454  "\nI want to offer you a tremendous ""thank yo...      0        0   

     threat                                         prediction  \
450       0   Toxic:\n    - 1\n  Obscene:\n    - 0\n  Threa...   
451       0  \n  Toxic:\n    - 0\n  Obscene:\n    - 0\n  Th...   
452       0  \nToxic:\n    - 0\n  Obscene:\n    - 0\n  Thre...   
453       0  \n  Toxic:\n    - 0\n  Obscene:\n    - 0\n  Th...   
454       0  \n  Toxic:\n    - 0\n  Obscene:\n    - 0\n  Th...   

    toxic_prediction obscene_prediction threat_prediction  
450                1                  0                 0  
451                0                  0                 0  
452                0                  0                 0  
453                0                  0                 0  
454                0                  0                 0

In [47]:
print('classification result for toxic comments \n')
y_test = test[test['toxic_prediction'].isin(['0','1'])]['toxic'].astype(str)
y_pred = test[test['toxic_prediction'].isin(['0','1'])]['toxic_prediction'].astype(str)
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

classification result for toxic comments 

[[201  22]
 [  7  19]]
              precision    recall  f1-score   support

           0       0.97      0.90      0.93       223
           1       0.46      0.73      0.57        26

    accuracy                           0.88       249
   macro avg       0.71      0.82      0.75       249
weighted avg       0.91      0.88      0.89       249



In [48]:
print('classification result for toxic comments \n')
y_test = test[test['obscene_prediction'].isin(['0','1'])]['obscene'].astype(str)
y_pred = test[test['obscene_prediction'].isin(['0','1'])]['obscene_prediction'].astype(str)
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

classification result for toxic comments 

[[237   1]
 [  6   5]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       238
           1       0.83      0.45      0.59        11

    accuracy                           0.97       249
   macro avg       0.90      0.73      0.79       249
weighted avg       0.97      0.97      0.97       249



In [49]:
print('classification result for toxic comments \n')
y_test = test[test['threat_prediction'].isin(['0','1'])]['threat'].astype(str)
y_pred = test[test['threat_prediction'].isin(['0','1'])]['threat_prediction'].astype(str)
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

classification result for toxic comments 

[[243   5]
 [  0   1]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       248
           1       0.17      1.00      0.29         1

    accuracy                           0.98       249
   macro avg       0.58      0.99      0.64       249
weighted avg       1.00      0.98      0.99       249

